### ISSUE TITLE
Performance regression in v1.7.0

### ISSUE THREAD

**Issue by JavaScriptBach** [masci/datadog#32]
When running on v1.7.0 of this action, all my calls take 1 minute to complete. In v1.6.0 and earlier, they took under a second.

I can provide more logs on request, but this action doesn't log any output so not sure what might be helpful.

**Comment by masci** [comment]
The CI confirms the performance regression, tests now take almost double the time on `master`:
- https://github.com/masci/datadog/actions

It looks like the culprit is the commit that bumped the node version to 20, I'll start investigating from there, thanks for reporting!

**Comment by masci** [comment]
I can reproduce locally, there's a timeout of 60s that hangs somewhere, I'll keep investigating

**Comment by masci** [comment]
@JavaScriptBach can you try again with 1.7.1?

**Comment by JavaScriptBach** [comment]
Works. Thanks!
