### ISSUE TITLE
Action version v1 is using node16

### ISSUE THREAD

**Issue by isindir** [masci/datadog#34]
Hello,

please release new version of plugin to move to `node20` which is on main branch, but the only version released is `v1` which is using `node16`. If possible please add section in Readme for potential compatibility issues while migrating from one version to another.

Thanks

**Comment by masci** [comment]
Hey @isindir thanks for reporting, node20 support is already in 1.7.1 but I forgot to point the `v1` tag there 🤦 

There was a performance regression in 1.7.0 that I hope I fixed in 1.71 (see #32), other than that, there are no breaking changes.

**Comment by erikzele** [comment]
@masci Thank you!

**Comment by isindir** [comment]
@masci Thank you! Checked it, looks good
